apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-deployment
  labels:
    app: quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus
  template:
    metadata:
      labels:
        app: quarkus
    spec:
      containers:
        - name: quarkus
          image: "wilda/hello-world-from-quarkus:{{ .Values.imageVersion }}"
          resources:
            requests:
              memory: "64Mi"
              cpu: "0"
            limits:
              memory: "512Mi"
              cpu: "500m"          
          ports:
            - name: http
              containerPort: 80
              protocol: TCP