apiVersion: v1
kind: Service
metadata:
  name: quarkus-service
spec:
  type: NodePort
  selector:
    app: quarkus
  ports:
    - port: 80
      targetPort: 8080
      nodePort: {{ .Values.service.port }}